custom: [ "https://www.chiaexplorer.com/blockchain/address/xch1lnnarj8tzx56fwe4gnds8365kj896a9tq08yt8pwsgqxczpqdkvs8n8dua",
          "https://www.chiaexplorer.com/blockchain/address/xch1c6rk9kh468stsf9vt4gxchndn5y5gesx8dk4mynwngqmd552hs6s870yes" ]
